/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.dork.app.react.api.model;

import java.util.Objects;
import com.dork.app.react.api.model.Content;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ActMessage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-16T04:20:57.379+01:00")
public class ActMessage {
  @SerializedName("receiverIds")
  private List<String> receiverIds = new ArrayList<String>();

  @SerializedName("description")
  private String description = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("0")
    NUMBER_0(0),
    
    @SerializedName("1")
    NUMBER_1(1);

    private Integer value;

    TypeEnum(Integer value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("content")
  private Content content = null;

  @SerializedName("senderId")
  private String senderId = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("dateCreated")
  private Long dateCreated = null;

  @SerializedName("dateReceived")
  private Long dateReceived = null;

  @SerializedName("dateViewed")
  private Long dateViewed = null;

  @SerializedName("id")
  private String id = null;

  public ActMessage receiverIds(List<String> receiverIds) {
    this.receiverIds = receiverIds;
    return this;
  }

  public ActMessage addReceiverIdsItem(String receiverIdsItem) {
    this.receiverIds.add(receiverIdsItem);
    return this;
  }

   /**
   * Get receiverIds
   * @return receiverIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getReceiverIds() {
    return receiverIds;
  }

  public void setReceiverIds(List<String> receiverIds) {
    this.receiverIds = receiverIds;
  }

  public ActMessage description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActMessage type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public ActMessage content(Content content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public Content getContent() {
    return content;
  }

  public void setContent(Content content) {
    this.content = content;
  }

  public ActMessage senderId(String senderId) {
    this.senderId = senderId;
    return this;
  }

   /**
   * Get senderId
   * @return senderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSenderId() {
    return senderId;
  }

  public void setSenderId(String senderId) {
    this.senderId = senderId;
  }

  public ActMessage tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public ActMessage addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public ActMessage dateCreated(Long dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Long dateCreated) {
    this.dateCreated = dateCreated;
  }

  public ActMessage dateReceived(Long dateReceived) {
    this.dateReceived = dateReceived;
    return this;
  }

   /**
   * Get dateReceived
   * @return dateReceived
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDateReceived() {
    return dateReceived;
  }

  public void setDateReceived(Long dateReceived) {
    this.dateReceived = dateReceived;
  }

  public ActMessage dateViewed(Long dateViewed) {
    this.dateViewed = dateViewed;
    return this;
  }

   /**
   * Get dateViewed
   * @return dateViewed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDateViewed() {
    return dateViewed;
  }

  public void setDateViewed(Long dateViewed) {
    this.dateViewed = dateViewed;
  }

  public ActMessage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActMessage actMessage = (ActMessage) o;
    return Objects.equals(this.receiverIds, actMessage.receiverIds) &&
        Objects.equals(this.description, actMessage.description) &&
        Objects.equals(this.type, actMessage.type) &&
        Objects.equals(this.content, actMessage.content) &&
        Objects.equals(this.senderId, actMessage.senderId) &&
        Objects.equals(this.tags, actMessage.tags) &&
        Objects.equals(this.dateCreated, actMessage.dateCreated) &&
        Objects.equals(this.dateReceived, actMessage.dateReceived) &&
        Objects.equals(this.dateViewed, actMessage.dateViewed) &&
        Objects.equals(this.id, actMessage.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiverIds, description, type, content, senderId, tags, dateCreated, dateReceived, dateViewed, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActMessage {\n");
    
    sb.append("    receiverIds: ").append(toIndentedString(receiverIds)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateReceived: ").append(toIndentedString(dateReceived)).append("\n");
    sb.append("    dateViewed: ").append(toIndentedString(dateViewed)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

