/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.dork.app.react.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ContactInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-18T18:49:45.404+01:00")
public class ContactInfo {
  @SerializedName("facebookAccount")
  private String facebookAccount = null;

  @SerializedName("googlePlusAccount")
  private String googlePlusAccount = null;

  @SerializedName("phoneNumbers")
  private List<String> phoneNumbers = new ArrayList<String>();

  @SerializedName("emails")
  private List<String> emails = new ArrayList<String>();

  public ContactInfo facebookAccount(String facebookAccount) {
    this.facebookAccount = facebookAccount;
    return this;
  }

   /**
   * Get facebookAccount
   * @return facebookAccount
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFacebookAccount() {
    return facebookAccount;
  }

  public void setFacebookAccount(String facebookAccount) {
    this.facebookAccount = facebookAccount;
  }

  public ContactInfo googlePlusAccount(String googlePlusAccount) {
    this.googlePlusAccount = googlePlusAccount;
    return this;
  }

   /**
   * Get googlePlusAccount
   * @return googlePlusAccount
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGooglePlusAccount() {
    return googlePlusAccount;
  }

  public void setGooglePlusAccount(String googlePlusAccount) {
    this.googlePlusAccount = googlePlusAccount;
  }

  public ContactInfo phoneNumbers(List<String> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public ContactInfo addPhoneNumbersItem(String phoneNumbersItem) {
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * Get phoneNumbers
   * @return phoneNumbers
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getPhoneNumbers() {
    return phoneNumbers;
  }

  public void setPhoneNumbers(List<String> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }

  public ContactInfo emails(List<String> emails) {
    this.emails = emails;
    return this;
  }

  public ContactInfo addEmailsItem(String emailsItem) {
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * Get emails
   * @return emails
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(List<String> emails) {
    this.emails = emails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactInfo contactInfo = (ContactInfo) o;
    return Objects.equals(this.facebookAccount, contactInfo.facebookAccount) &&
        Objects.equals(this.googlePlusAccount, contactInfo.googlePlusAccount) &&
        Objects.equals(this.phoneNumbers, contactInfo.phoneNumbers) &&
        Objects.equals(this.emails, contactInfo.emails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facebookAccount, googlePlusAccount, phoneNumbers, emails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactInfo {\n");
    
    sb.append("    facebookAccount: ").append(toIndentedString(facebookAccount)).append("\n");
    sb.append("    googlePlusAccount: ").append(toIndentedString(googlePlusAccount)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

