/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.dork.app.react.api;

import com.dork.app.react.api.invoker.ApiException;
import com.dork.app.react.api.model.LoginCredentials;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiAuthLoginPostTest() throws ApiException {
        LoginCredentials loginCredentials = null;
        Boolean response = api.apiAuthLoginPost(loginCredentials);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiAuthLogoutPostTest() throws ApiException {
        api.apiAuthLogoutPost();

        // TODO: test validations
    }
    
}
