/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.dork.app.react.cookie;

import com.dork.app.react.cookie.invoker.ApiException;
import com.dork.app.react.cookie.model.Profile;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for ProfileApi
 */
@Ignore
public class ProfileApiTest {

    private final ProfileApi api = new ProfileApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiProfileProfileByIdGetTest() throws ApiException {
        String id = null;
        Profile response = api.apiProfileProfileByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiProfileProfileCreatePostTest() throws ApiException {
        Profile profile = null;
        Long response = api.apiProfileProfileCreatePost(profile);

        // TODO: test validations
    }
    
}
